dev:
  build: tools/
  ports:
    - "4000:4000"
  volumes:
    - ./build:/hackathon-site/build
    - ./api-server:/hackathon-site/api-server
    - ./tools:/hackathon-site/tools
    - ./web:/hackathon-site/web
  tty: true
  working_dir: /hackathon-site
